### ISSUE TITLE
Networking issue from BP notebook - can't get source control connection

### ISSUE THREAD

**Issue by jokeeffeBP** [jokeeffeBP/azure-charliebravo-jok#1]
13:30:31 - [ERROR] New-AzureRmResourceGroupDeployment : 1:30:31 PM - Resource 
13:30:31 - [ERROR] Microsoft.Web/sites/slots/sourcecontrols 'JOK-PaaS-2Tier-VC-2-WA/Staging/web' 
13:30:31 - [ERROR] failed with message 'Repository 'UpdateSiteSourceControl' operation failed 
13:30:31 - [ERROR] with System.Net.WebException: The remote server returned an error: (502) Bad 
13:30:31 - [ERROR] Gateway.
13:30:31 - [ERROR]    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
13:30:31 - [ERROR]    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult 
13:30:31 - [ERROR] iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean 
13:30:31 - [ERROR] requiresSynchronization)
13:30:31 - [ERROR] --- End of stack trace from previous location where exception was thrown ---
13:30:31 - [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:30:31 - [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
13:30:31 - [ERROR] tification(Task task)
13:30:31 - [ERROR]    at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContex
13:30:31 - [ERROR] t.<GetResponseAsync>d__6d.MoveNext()
13:30:31 - [ERROR] --- End of stack trace from previous location where exception was thrown ---
13:30:31 - [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:30:31 - [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
13:30:31 - [ERROR] tification(Task task)
13:30:31 - [ERROR]    at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsA
13:30:31 - [ERROR] sync>d__3b.MoveNext()
13:30:31 - [ERROR] --- End of stack trace from previous location where exception was thrown ---
13:30:31 - [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:30:31 - [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
13:30:31 - [ERROR] tification(Task task)
13:30:31 - [ERROR]    at Microsoft.Web.Hosting.Administration.GitHubSiteRepositoryProvider.<Update
13:30:31 - [ERROR] SiteSourceControl>d__6.MoveNext().'
13:30:31 - [ERROR] At C:\users\james\documents\visual studio 2015\projects\jok-paas-2tier-vc-app\j
13:30:31 - [ERROR] ok-paas-2tier-vc-rg\Scripts\Deploy-AzureResourceGroup.ps1:100 char:1
13:30:31 - [ERROR] + New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFil ...
13:30:31 - [ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13:30:31 - [ERROR]     + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeplo 
13:30:31 - [ERROR]    yment], Exception
13:30:31 - [ERROR]     + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResou 
13:30:31 - [ERROR]    rceGroupDeploymentCommand
13:30:31 - [ERROR]

**Comment by jokeeffeBP** [comment]
Transient
